final

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,10 +1,19 @@
 language: haskell
 
+env:
+ - GHCVER=7.6.3 CABALVER=1.16
+ - GHCVER=7.8.2 CABALVER=1.18
+ - GHCVER=head  CABALVER=1.20
+
+matrix:
+  allow_failures:
+   - env: GHCVER=head  CABALVER=1.20
+
 befor_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-1.18 ghc-7.8.2
- - export PATH=/opt/ghc/7.8.2/bin:/opt/cabal/1.18/bin:$PATH
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal --version
 
 install:
@@ -15,8 +24,18 @@ install:
 script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
+ - cabal sdist
  - run-cabal-test --show-details=always
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   (cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi)
 
 after_script:
+#ln -s dist/hpc/mix/Dir_Name ./dist/hpc/mix/text
  - ln -s dist/hpc/mix/conduit-1.0.8 ./dist/hpc/mix/text
- - hpc-coveralls test
+ - hpc-coveralls --exclude-dir=test test
